_wandb:
    value:
        cli_version: 0.25.0
        e:
            z3gnjqyi9na1lm92wbb2y79wuxwk38vp:
                codePath: da6401_colab.ipynb
                codePathLocal: da6401_colab.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1ez_vjkcsG3W2PCsJrCjy_XSfUBJY7l6I
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "120942624768"
                        used: "44789559296"
                email: ma24m015@smail.iitm.ac.in
                executable: /usr/bin/python3
                git:
                    commit: f098a75ae0bcc0fc3f3a11571a0f7b6b9c1459a1
                    remote: https://github.com/shadab007-byte/da6401_assignment_1.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-adad963c-14bc-0a7c-015b-bb85f61c142c
                host: 2cd07325f6a2
                memory:
                    total: "13605851136"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: da6401_colab.ipynb
                python: CPython 3.12.12
                root: /content/da6401_assignment_1
                startedAt: "2026-02-26T08:23:24.583768Z"
                writerId: z3gnjqyi9na1lm92wbb2y79wuxwk38vp
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "8":
                - 1
                - 12
            "12": 0.25.0
            "13": linux-x86_64
lr:
    value: 0.001
optimizer:
    value: nadam
